uint32[2] firsthourupleft
uint32[2] firsthourupright
uint32[2] firsthourbottomleft
uint32[2] firsthourbottomright

uint32[2] secondhourupleft
uint32[2] secondhourupright
uint32[2] secondhourbottomleft
uint32[2] secondhourbottomright

uint32[2] thirdhourupleft
uint32[2] thirdhourupright
uint32[2] thirdhourbottomleft
uint32[2] thirdhourbottomright

uint32[2] firstkgupleft
uint32[2] firstkgupright
uint32[2] firstkgbottomleft
uint32[2] firstkgbottomright

uint32[2] secondkgupleft
uint32[2] secondkgupright
uint32[2] secondkgbottomleft
uint32[2] secondkgbottomright

uint32[2] firsttempupleft
uint32[2] firsttempupright
uint32[2] firsttempbottomleft
uint32[2] firsttempbottomright

uint32[2] secondtempupleft
uint32[2] secondtempupright
uint32[2] secondtempbottomleft
uint32[2] secondtempbottomright

uint32[2] firstcentrupleft
uint32[2] firstcentrupright
uint32[2] firstcentrbottomleft
uint32[2] firstcentrbottomright

uint32[2] secondcentrupleft
uint32[2] secondcentrupright
uint32[2] secondcentrbottomleft
uint32[2] secondcentrbottomright

uint32[2] thirdcentrupleft
uint32[2] thirdcentrupright
uint32[2] thirdcentrbottomleft
uint32[2] thirdcentrbottomright

uint32[2] fourthcentrupleft
uint32[2] fourthcentrupright
uint32[2] fourthcentrbottomleft
uint32[2] fourthcentrbottomright

uint32[2] speedupleft
uint32[2] speedupright
uint32[2] speedbottomleft
uint32[2] speedbottomright







